//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoTierraMedia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancoTierraMedia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap book {
            get {
                object obj = ResourceManager.GetObject("book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aldburg
        ///Almaida
        ///Alqualondë
        ///Andúnië
        ///Annúminas
        ///Armenelos
        ///Avallónë
        ///Belegost
        ///Bree
        ///Brithombar
        ///Budgeford
        ///Calembel
        ///Caras Galadhon
        ///Carn Dûm
        ///Combe
        ///Dale
        ///Dol Amroth
        ///Dol Guldur
        ///Dunharrow
        ///Edhellond
        ///Edoras
        ///Eglarest
        ///Eldalondë
        ///Ephel Brandir
        ///Esgaroth
        ///Ethring
        ///Forlond
        ///Formenos
        ///Fornost
        ///Framsburg
        ///Galabas
        ///Goblin Town
        ///Gondolin
        ///Harlond
        ///Havens of Sirion
        ///Havens of the Falas
        ///Helm&apos;s Deep
        ///Hobbiton
        ///Hyarastorni
        ///Isengard
        ///Linhir
        ///Lothlorien
        ///Minas Morgul
        ///Minas Tirith
        ///Mithlond
        ///Moria
        ///Mordor
        ///Nindam [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lugares {
            get {
                return ResourceManager.GetString("lugares", resourceCulture);
            }
        }
    }
}
